// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef fltdj_h
#define fltdj_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *alertwin;
#include <FL/Fl_Output.H>
extern Fl_Output *alertbox;
#include <FL/Fl_Button.H>
extern void alert_cb(Fl_Button*, void*);
extern Fl_Button *alertbutton;
#include "fltdjfunctions.h"
extern void window_cb(Fl_Double_Window*, void*);
extern Fl_Double_Window *mainwin;
#include <FL/Fl_Group.H>
extern Fl_Group *calgroup;
#include <FL/Fl_Clock.H>
extern Fl_Clock *Oclock;
#include <FL/Fl_Box.H>
extern Fl_Box *yeartext;
extern void cal(Fl_Button*, long);
extern Fl_Button *yeardownbutton;
extern Fl_Button *yearupbutton;
extern Fl_Box *monthtext;
extern Fl_Button *monthdownbutton;
extern Fl_Button *monthupbutton;
extern void datebutton(Fl_Button*, long);
extern Fl_Button *day[38];
extern Fl_Box *currentdate;
extern void buttons(Fl_Button*, void*);
extern Fl_Button *exitbut;
extern Fl_Button *helpbut;
#include "cmultitabs.h"
extern void tab_cb(CMultiTabs*, void*);
extern CMultiTabs *basetab;
extern Fl_Group *journaltab;
extern void note_buttons(Fl_Button*, void*);
extern Fl_Button *prevnote;
extern Fl_Button *nextnote;
extern Fl_Box *notedaydatedisplayed1;
extern Fl_Box *todaysholiday1;
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *noteditor;
extern Fl_Group *apptab;
extern Fl_Box *notedaydatedisplayed2;
extern Fl_Box *todaysholiday2;
extern Fl_Box *appttime[10];
extern Fl_Box *apptname[10];
#include <FL/Fl_Int_Input.H>
extern void appt_cb(Fl_Int_Input*, void*);
extern Fl_Int_Input *appttimein;
#include <FL/Fl_Input.H>
extern void appt_cb(Fl_Input*, void*);
extern Fl_Input *apptnamein;
extern void appt_cb(Fl_Button*, void*);
extern Fl_Button *apptaddbut;
extern Fl_Button *apptmodifybut;
extern Fl_Button *apptdeletebut;
extern Fl_Button *apptprevbut;
extern Fl_Button *apptnextbut;
extern void appt_cb(Fl_Box*, void*);
extern Fl_Box *apptnum;
extern Fl_Button *prevdayapp;
extern Fl_Button *nextdayapp;
extern Fl_Group *contab;
extern Fl_Box *contactkey;
extern void contact_cb(Fl_Button*, void*);
extern Fl_Button *contactkeylistbut;
extern Fl_Text_Editor *contacteditor;
#include <FL/Fl_Select_Browser.H>
extern void contact_cb(Fl_Select_Browser*, void*);
extern Fl_Select_Browser *contactkeylist;
extern Fl_Button *contactprevbut;
extern Fl_Button *contactnextbut;
extern Fl_Box *contactnum;
extern Fl_Button *contactaddbut;
extern Fl_Button *contactmodifybut;
extern Fl_Button *contactdeletebut;
extern Fl_Group *todotab;
extern Fl_Text_Editor *todoeditor;
extern Fl_Group *holtab;
extern Fl_Box *holdate[10];
extern Fl_Box *holmonth[10];
extern Fl_Box *holtext[10];
extern void hol_cb(Fl_Int_Input*, void*);
extern Fl_Int_Input *holdatein;
extern Fl_Int_Input *holmonthin;
extern void hol_cb(Fl_Input*, void*);
extern Fl_Input *holtextin;
extern void hol_cb(Fl_Button*, void*);
extern Fl_Button *holaddbut;
extern Fl_Button *holdeletebut;
extern Fl_Button *holprevbut;
extern Fl_Button *holnextbut;
extern Fl_Box *holnum;
extern Fl_Group *searchtab;
extern Fl_Output *searchtext;
#include <FL/Fl_Browser.H>
extern void searchlistshow_cb(Fl_Browser*, void*);
extern Fl_Browser *journalsearchresultlist;
extern Fl_Browser *apptsearchresultlist;
extern Fl_Group *preftab;
extern void pref_cb(Fl_Button*, void*);
extern Fl_Button *applybut;
extern Fl_Button *savebut;
#include <FL/Fl_Check_Button.H>
extern void pref_cb(Fl_Check_Button*, void*);
extern Fl_Check_Button *fortune;
extern Fl_Box *fonttextbox;
#include <FL/Fl_Slider.H>
extern void pref_cb(Fl_Slider*, void*);
extern Fl_Slider *fontsizeslider;
extern Fl_Slider *fontslider;
extern Fl_Group *helptab;
#include <FL/Fl_Help_View.H>
extern Fl_Help_View *help;
extern Fl_Group *abouttab;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *gnugplicense;
extern Fl_Group *findgroup;
extern Fl_Button *findbut;
extern Fl_Input *findtextbox;
Fl_Double_Window* create_the_ui();
#endif
